FROM node:25.6.0-slim

RUN apt update \
    && apt install -y --no-install-recommends procps curl ffmpeg \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /home/node/app
RUN chown -R node:node /home/node/app

COPY --chown=node:node package*.json ./

USER node

RUN npm ci

CMD [ "npm", "run", "start:dev" ]
